### ISSUE TITLE
edge.yaml config ideas

### ISSUE THREAD

**Issue by Ehesp** [invertase/dart_edge#12]
By default no config is required when developing and deploying, however providing such a file would allow the CLI to hook onto various options:

- [ ] Support multiple entry points. For example, `lib/admin.dart` could deploy as it's own standalone function. Currently, only a single entrypoint is supported.

**Comment by venkata-reddy-dev** [comment]
I think we can provide different entry points by configuring `edge.yml` file 

```
supabase:
  functions:
    task1: 'lib/task1.dart'
    task2: 'lib/task2.dart'
  projectPath: "supabase"
```
