### ISSUE TITLE
edge build supabase_functions doesn't work

### ISSUE THREAD

**Issue by solid-danylokhvan** [invertase/dart_edge#36]
**pubspec.yaml**: 
```
environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  edge: ^0.0.6
  edge_http_client: ^0.0.1+1
  supabase: ^1.6.3
  supabase_functions: ^0.0.1+1
dependency_overrides: 
  edge:
    git:
      url: https://github.com/invertase/dart_edge.git
      ref: main
      path: packages/edge
  supabase_functions:
    git:
      url: https://github.com/invertase/dart_edge.git
      ref: main
      path: packages/supabase_functions
```

I can not make a build with the command `edge build supabase_functions` after the recent fix still
