### ISSUE TITLE
Not working as per superbase Docs

### ISSUE THREAD

**Issue by venkata-reddy-dev** [invertase/dart_edge#58]
I have fallowed the docs of superbase to run dart edge in superbase platform. but even hello world function also not working 

doc: https://supabase.com/docs/guides/functions/dart-edge

<img width="1410" alt="Screenshot 2023-11-07 at 7 35 07 PM" src="https://github.com/invertase/dart_edge/assets/32235964/59da7a13-bdda-4011-b1c1-07ff84630f82">

**Comment by yoohoomedia** [comment]
The function is being served on:
` http://127.0.0.1:54321/functions/v1`

but your url is missing the **/v1**.

**Comment by venkata-reddy-dev** [comment]
https://github.com/invertase/dart_edge/issues/52#issuecomment-1834515475 helped me as a temporary fix

**Comment by venkata-reddy-dev** [comment]
Finally worked after defining `edge.yml` configuration as below.

```
supabase:
  functions:
    task1: 'lib/task1.dart'
    task2: 'lib/task2.dart'
  projectPath: "supabase"
```
